#ifndef EXTENSION_REGISTRY_H_INCLUDED
#define EXTENSION_REGISTRY_H_INCLUDED
/*
#include <declspec.h>

#if (defined WIN32) || (defined _WIN32) || (defined __WIN32__)
  #include <Windows.h>
#endif

// Bootstrap function for OpenGL 3.0 and greater
#define glGetStringi opengl_core_GetStringi;

// OpenGL 1.2
#define glMinmax opengl_core_Minmax;
#define glGetMinmax opengl_core_GetMinmax;
#define glHistorgram opengl_core_Histogram;
#define glBlendColor opengl_core_BlendColor;
#define glColorTable opengl_core_ColorTable;
#define glTexImage3D opengl_core_TexImage3D;
#define glResetMinmax opengl_core_ResetMinmax;
#define glGetHistogram opengl_core_GetHistogram;
#define glBlendEquation opengl_core_BlendEquation;
#define glGetColorTable opengl_core_GetColorTable;
#define glColorSubTable opengl_core_ColorSubTable;
#define glTextSubImage3D opengl_core_TexSubImage3D;
#define glCopyColorTable opengl_core_CopyColorTable;
#define glResetHistorgram opengl_core_ResetHistogram;
#define glDrawRangeElements opengl_core_DrawRangeElements;
#define glCopyColorSubTable opengl_core_CopyColorSubTable;
#define glSeparableFilter2D opengl_core_SeparableFilter2D;
#define glCopyTexSubImage3D opengl_core_CopyTexSubImage3D;
#define glGetSeparabaleFilter opengl_core_GetSeparableFilter;
#define glConvolutionFilter1D opengl_core_ConvolutionFilter1D;
#define glConvolutionFilter2D opengl_core_ConvolutionFilter2D;
#define glGetConvolutionFilter opengl_core_GetConvolutionFilter;
#define glGetMinmaxParameterfv opengl_core_GetMinmaxParameterfv;
#define glGetMinmaxParameteriv opengl_core_GetMinmaxParameteriv;
#define glColorTableParameterfv opengl_core_ColorTableParameterfv;
#define glColorTableParameteriv opengl_core_ColorTableParameteriv;
#define glConvolutionParameterf opengl_core_ConvolutionParameterf;
#define glConvolutionParameteri opengl_core_ConvolutionParameteri;
#define glConvolutionParameterfv opengl_core_ConvolutionParameterfv;
#define glConvolutionParameteriv opengl_core_ConvolutionParameteriv;
#define glCopyConvolutionFilter1D opengl_core_CopyConvolutionFilter1D;
#define glCopyConvolutionFilter2D opengl_core_CopyConvolutionFilter2D;
#define glGetHistogramParameterfv opengl_core_GetHistogramParameterfv;
#define glGetHistogramParameteriv opengl_core_GetHistogramParameteriv;
#define glGetColorTableParameterfv opengl_core_GetColorTableParameterfv;
#define glGetColorTableParameteriv opengl_core_GetColorTableParameteriv;
#define glGetConvolutionParameterfv opengl_core_GetConvolutionParameterfv;
#define glGetConvolutionParameteriv opengl_core_GetConvolutionParameteriv;

// OpenGL 1.3
#define glActiveTexture opengl_core_ActiveTexture
#define glSampleCoverage opengl_core_SampleCoverage
#define glMultiTexCoord1d opengl_core_MultiTexCoord1d
#define glMultiTexCoord1f opengl_core_MultiTexCoord1f
#define glMultiTexCoord1i opengl_core_MultiTexCoord1i
#define glMultiTexCoord1s opengl_core_MultiTexCoord1s
#define glMultiTexCoord2d opengl_core_MultiTexCoord2d
#define glMultiTexCoord2f opengl_core_MultiTexCoord2f
#define glMultiTexCoord2i opengl_core_MultiTexCoord2i
#define glMultiTexCoord2s opengl_core_MultiTexCoord2s
#define glMultiTexCoord3d opengl_core_MultiTexCoord3d
#define glMultiTexCoord3f opengl_core_MultiTexCoord3f
#define glMultiTexCoord3i opengl_core_MultiTexCoord3i
#define glMultiTexCoord3s opengl_core_MultiTexCoord3s
#define glMultiTexCoord4d opengl_core_MultiTexCoord4d
#define glMultiTexCoord4f opengl_core_MultiTexCoord4f
#define glMultiTexCoord4i opengl_core_MultiTexCoord4i
#define glMultiTexCoord4s opengl_core_MultiTexCoord4s
#define glMultiTexCoord1dv opengl_core_MultiTexCoord1dv
#define glMultiTexCoord1fv opengl_core_MultiTexCoord1fv
#define glMultiTexCoord1iv opengl_core_MultiTexCoord1iv
#define glMultiTexCoord1sv opengl_core_MultiTexCoord1sv
#define glMultiTexCoord2dv opengl_core_MultiTexCoord2dv
#define glMultiTexCoord2fv opengl_core_MultiTexCoord2fv
#define glMultiTexCoord2iv opengl_core_MultiTexCoord2iv
#define glMultiTexCoord2sv opengl_core_MultiTexCoord2sv
#define glMultiTexCoord3dv opengl_core_MultiTexCoord3dv
#define glMultiTexCoord3fv opengl_core_MultiTexCoord3fv
#define glMultiTexCoord3iv opengl_core_MultiTexCoord3iv
#define glMultiTexCoord3sv opengl_core_MultiTexCoord3sv
#define glMultiTexCoord4dv opengl_core_MultiTexCoord4dv
#define glMultiTexCoord4fv opengl_core_MultiTexCoord4fv
#define glMultiTexCoord4iv opengl_core_MultiTexCoord4iv
#define glMultiTexCoord4sv opengl_core_MultiTexCoord4sv
#define glClientActiveTexture opengl_core_ClientActiveTexture
#define glLoadTransposeMatrixf opengl_core_LoadTransposeMatrixf
#define glLoadTransposeMatrixd opengl_core_LoadTransposeMatrixd
#define glMultTransposeMatrixf opengl_core_MultTransposeMatrixf
#define glMultTransposeMatrixd opengl_core_MultTransposeMatrixd
#define glCompressedTexImage3D opengl_core_CompressedTexImage3D
#define glCompressedTexImage2D opengl_core_CompressedTexImage2D
#define glCompressedTexImage1D opengl_core_CompressedTexImage1D
#define glCompressedTexSubImage3D opengl_core_CompressedTexSubImage3D
#define glCompressedTexSubImage2D opengl_core_CompressedTexSubImage2D
#define glCompressedTexSubImage1D opengl_core_CompressedTexSubImage1D

// OpenGL 1.4
#define glFogCoordf opengl_core_FogCoordf
#define glFogCoordd opengl_core_FogCoordd
#define glFogCoordfv opengl_core_FogCoordfv
#define glFogCoorddv opengl_core_FogCoorddv
#define glWindowPos2d opengl_core_WindowPos2d
#define glWindowPos2f opengl_core_WindowPos2f
#define glWindowPos2i opengl_core_WindowPos2i
#define glWindowPos2s opengl_core_WindowPos2s
#define glWindowPos3d opengl_core_WindowPos3d
#define glWindowPos3f opengl_core_WindowPos3f
#define glWindowPos3i opengl_core_WindowPos3i
#define glWindowPos3s opengl_core_WindowPos3s
#define glWindowPos2dv opengl_core_WindowPos2dv
#define glWindowPos2fv opengl_core_WindowPos2fv
#define glWindowPos2iv opengl_core_WindowPos2iv
#define glWindowPos2sv opengl_core_WindowPos2sv
#define glWindowPos3dv opengl_core_WindowPos3dv
#define glWindowPos3fv opengl_core_WindowPos3fv
#define glWindowPos3iv opengl_core_WindowPos3iv
#define glWindowPos3sv opengl_core_WindowPos3sv
#define glFogCoordPointer opengl_core_FogCoordPointer
#define glMultiDrawArrays opengl_core_MultiDrawArrays
#define glPointParameterf opengl_core_PointParameterf
#define glPointParameteri opengl_core_PointParameteri
#define glPointParameterfv opengl_core_PointParameterfv
#define glPointParameteriv opengl_core_PointParameteriv
#define glSecondaryColor3b opengl_core_SecondaryColor3b
#define glSecondaryColor3d opengl_core_SecondaryColor3d
#define glSecondaryColor3f opengl_core_SecondaryColor3f
#define glSecondaryColor3i opengl_core_SecondaryColor3i
#define glSecondaryColor3s opengl_core_SecondaryColor3s
#define glBlendFuncSeparate opengl_core_BlendFuncSeparate
#define glMultiDrawElements opengl_core_MultiDrawElements
#define glSecondaryColor3bv opengl_core_SecondaryColor3bv
#define glSecondaryColor3dv opengl_core_SecondaryColor3dv
#define glSecondaryColor3fv opengl_core_SecondaryColor3fv
#define glSecondaryColor3iv opengl_core_SecondaryColor3iv
#define glSecondaryColor3sv opengl_core_SecondaryColor3sv
#define glSecondaryColor3ub opengl_core_SecondaryColor3ub
#define glSecondaryColor3ui opengl_core_SecondaryColor3ui
#define glSecondaryColor3us opengl_core_SecondaryColor3us
#define glSecondaryColor3ubv opengl_core_SecondaryColor3ubv
#define glSecondaryColor3uiv opengl_core_SecondaryColor3uiv
#define glSecondaryColor3usv opengl_core_SecondaryColor3usv
#define glSecondaryColorPointer opengl_core_SecondaryColorPointer

// OpenGL 1.5
#define glIsQuery opengl_core_IsQuery
#define glEndQuery opengl_core_EndQuery
#define glIsBuffer opengl_core_IsBuffer
#define glMapBuffer opengl_core_MapBuffer
#define glGenQueries opengl_core_GenQueries
#define glBeginQuery opengl_core_BeginQuery
#define glGetQueryiv opengl_core_GetQueryiv
#define glBindBuffer opengl_core_BindBuffer
#define glGenBuffers opengl_core_GenBuffers
#define glBufferData opengl_core_BufferData
#define glUnmapBuffer opengl_core_UnmapBuffer
#define glDeleteQueries opengl_core_DeleteQueries
#define glDeleteBuffers opengl_core_DeleteBuffers
#define glBufferSubData opengl_core_BufferSubData
#define glGetQueryObjectiv opengl_core_GetQueryObjectiv
#define glGetBufferSubData opengl_core_GetBufferSubData
#define glGetQueryObjectuiv opengl_core_GetQueryObjectuiv
#define glGetBufferPointerv opengl_core_GetBufferPointerv
#define glGetBufferParameteriv opengl_core_GetBufferParameteriv

// OpenGL 2.0
#define glIsShader opengl_core_IsShader
#define glIsProgram opengl_core_IsProgram
#define glUniform1f opengl_core_Uniform1f
#define glUniform2f opengl_core_Uniform2f
#define glUniform3f opengl_core_Uniform3f
#define glUniform4f opengl_core_Uniform4f
#define glUniform1i opengl_core_Uniform1i
#define glUniform2i opengl_core_Uniform2i
#define glUniform3i opengl_core_Uniform3i
#define glUniform4i opengl_core_Uniform4i
#define glUseProgram opengl_core_UseProgram
#define glUniform1fv opengl_core_Uniform1fv
#define glUniform2fv opengl_core_Uniform2fv
#define glUniform3fv opengl_core_Uniform3fv
#define glUniform4fv opengl_core_Uniform4fv
#define glUniform1iv opengl_core_Uniform1iv
#define glUniform2iv opengl_core_Uniform2iv
#define glUniform3iv opengl_core_Uniform3iv
#define glUniform4iv opengl_core_Uniform4iv
#define glDrawBuffers opengl_core_DrawBuffers
#define glGetShaderiv opengl_core_GetShaderiv
#define glLinkProgram opengl_core_LinkProgram
#define glAttachShader opengl_core_AttachShader
#define glCreateShader opengl_core_CreateShader
#define glDeleteShader opengl_core_DeleteShader
#define glDetachShader opengl_core_DetachShader
#define glGetProgramiv opengl_core_GetProgramiv
#define glGetUniformfv opengl_core_GetUniformfv
#define glGetUniformiv opengl_core_GetUniformiv
#define glShaderSource opengl_core_ShaderSource
#define glCompileShader opengl_core_CompileShader
#define glCreateProgram opengl_core_CreateProgram
#define glDeleteProgram opengl_core_DeleteProgram
#define glVertexAttrib1d opengl_core_VertexAttrib1d
#define glVertexAttrib1f opengl_core_VertexAttrib1f
#define glVertexAttrib1s opengl_core_VertexAttrib1s
#define glVertexAttrib2d opengl_core_VertexAttrib2d
#define glVertexAttrib2f opengl_core_VertexAttrib2f
#define glVertexAttrib2s opengl_core_VertexAttrib2s
#define glVertexAttrib3d opengl_core_VertexAttrib3d
#define glVertexAttrib3f opengl_core_VertexAttrib3f
#define glVertexAttrib3s opengl_core_VertexAttrib3s
#define glVertexAttrib4d opengl_core_VertexAttrib4d
#define glVertexAttrib4f opengl_core_VertexAttrib4f
#define glVertexAttrib4s opengl_core_VertexAttrib4s
#define glGetActiveAttrib opengl_core_GetActiveAttrib
#define glGetShaderSource opengl_core_GetShaderSource
#define glValidateProgram opengl_core_ValidateProgram
#define glVertexAttrib1dv opengl_core_VertexAttrib1dv
#define glVertexAttrib1fv opengl_core_VertexAttrib1fv
#define glVertexAttrib1sv opengl_core_VertexAttrib1sv
#define glVertexAttrib2dv opengl_core_VertexAttrib2dv
#define glVertexAttrib2fv opengl_core_VertexAttrib2fv
#define glVertexAttrib2sv opengl_core_VertexAttrib2sv
#define glVertexAttrib3dv opengl_core_VertexAttrib3dv
#define glVertexAttrib3fv opengl_core_VertexAttrib3fv
#define glVertexAttrib3sv opengl_core_VertexAttrib3sv
#define glVertexAttrib4bv opengl_core_VertexAttrib4bv
#define glVertexAttrib4dv opengl_core_VertexAttrib4dv
#define glVertexAttrib4fv opengl_core_VertexAttrib4fv
#define glVertexAttrib4iv opengl_core_VertexAttrib4iv
#define glVertexAttrib4sv opengl_core_VertexAttrib4sv
#define glGetActiveUniform opengl_core_GetActiveUniform
#define glGetShaderInfoLog opengl_core_GetShaderInfoLog
#define glUniformMatrix2fv opengl_core_UniformMatrix2fv
#define glUniformMatrix3fv opengl_core_UniformMatrix3fv
#define glUniformMatrix4fv opengl_core_UniformMatrix4fv
#define glVertexAttrib4Nbv opengl_core_VertexAttrib4Nbv
#define glVertexAttrib4Niv opengl_core_VertexAttrib4Niv
#define glVertexAttrib4Nsv opengl_core_VertexAttrib4Nsv
#define glVertexAttrib4Nub opengl_core_VertexAttrib4Nub
#define glVertexAttrib4ubv opengl_core_VertexAttrib4ubv
#define glVertexAttrib4uiv opengl_core_VertexAttrib4uiv
#define glVertexAttrib4usv opengl_core_VertexAttrib4usv
#define glStencilOpSeparate opengl_core_StencilOpSeparate
#define glGetAttribLocation opengl_core_GetAttribLocation
#define glGetProgramInfoLog opengl_core_GetProgramInfoLog
#define glGetVertexAttribdv opengl_core_GetVertexAttribdv
#define glGetVertexAttribfv opengl_core_GetVertexAttribfv
#define glGetVertexAttribiv opengl_core_GetVertexAttribiv
#define glVertexAttrib4Nubv opengl_core_VertexAttrib4Nubv
#define glVertexAttrib4Nuiv opengl_core_VertexAttrib4Nuiv
#define glVertexAttrib4Nusv opengl_core_VertexAttrib4Nusv
#define glBindAttribLocation opengl_core_BindAttribLocation
#define glGetAttachedShaders opengl_core_GetAttachedShaders
#define glGetUniformLocation opengl_core_GetUniformLocation
#define glStencilFuncSeparate opengl_core_StencilFuncSeparate
#define glStencilMaskSeparate opengl_core_StencilMaskSeparate
#define glVertexAttribPointer opengl_core_VertexAttribPointer
#define glBlendEquationSeparate opengl_core_BlendEquationSeparate
#define glEnableVertexAttribArray opengl_core_EnableVertexAttribArray
#define glGetVertexAttribPointerv opengl_core_GetVertexAttribPointerv
#define glDisableVertexAttribArray opengl_core_DisableVertexAttribArray

// OpenGL 2.1
#define glUniformMatrix2x3fv opengl_core_UniformMatrix2x3fv
#define glUniformMatrix3x2fv opengl_core_UniformMatrix3x2fv
#define glUniformMatrix2x4fv opengl_core_UniformMatrix2x4fv
#define glUniformMatrix4x2fv opengl_core_UniformMatrix4x2fv
#define glUniformMatrix3x4fv opengl_core_UniformMatrix3x4fv
#define glUniformMatrix4x3fv opengl_core_UniformMatrix4x3fv

// OpenGL 3.0
// OpenGL 3.0 also reuses entry points from these extensions:
//  ARB_framebuffer_object
//  ARB_map_buffer_range
//  ARB_vertex_array_object
#define glEnablei opengl_core_Enablei
#define glDisablei opengl_core_Disablei
#define glColorMaski opengl_core_ColorMaski
#define glIsEnabledi opengl_core_IsEnabledi
#define glClampColor opengl_core_ClampColor
#define glUniform1ui opengl_core_Uniform1ui
#define glUniform2ui opengl_core_Uniform2ui
#define glUniform3ui opengl_core_Uniform3ui
#define glUniform4ui opengl_core_Uniform4ui
#define glUniform1uiv opengl_core_Uniform1uiv
#define glUniform2uiv opengl_core_Uniform2uiv
#define glUniform3uiv opengl_core_Uniform3uiv
#define glUniform4uiv opengl_core_Uniform4uiv
#define glGetBooleani_v opengl_core_GetBooleani_v
#define glGetIntegeri_v opengl_core_GetIntegeri_v
#define glGetUniformuiv opengl_core_GetUniformuiv
#define glClearBufferiv opengl_core_ClearBufferiv
#define glClearBufferfv opengl_core_ClearBufferfv
#define glClearBufferfi opengl_core_ClearBufferfi
#define glBindBufferBase opengl_core_BindBufferBase
#define glClearBufferuiv opengl_core_ClearBufferuiv
#define glBindBufferRange opengl_core_BindBufferRange
#define glVertexAttribI1i opengl_core_VertexAttribI1i
#define glVertexAttribI2i opengl_core_VertexAttribI2i
#define glVertexAttribI3i opengl_core_VertexAttribI3i
#define glVertexAttribI4i opengl_core_VertexAttribI4i
#define glTexParameterIiv opengl_core_TexParameterIiv
#define glVertexAttribI1ui opengl_core_VertexAttribI1ui
#define glVertexAttribI2ui opengl_core_VertexAttribI2ui
#define glVertexAttribI3ui opengl_core_VertexAttribI3ui
#define glVertexAttribI4ui opengl_core_VertexAttribI4ui
#define glVertexAttribI1iv opengl_core_VertexAttribI1iv
#define glVertexAttribI2iv opengl_core_VertexAttribI2iv
#define glVertexAttribI3iv opengl_core_VertexAttribI3iv
#define glVertexAttribI4iv opengl_core_VertexAttribI4iv
#define glVertexAttribI4bv opengl_core_VertexAttribI4bv
#define glVertexAttribI4sv opengl_core_VertexAttribI4sv
#define glTexParameterIuiv opengl_core_TexParameterIuiv
#define glVertexAttribI1uiv opengl_core_VertexAttribI1uiv
#define glVertexAttribI2uiv opengl_core_VertexAttribI2uiv
#define glVertexAttribI3uiv opengl_core_VertexAttribI3uiv
#define glVertexAttribI4uiv opengl_core_VertexAttribI4uiv
#define glVertexAttribI4ubv opengl_core_VertexAttribI4ubv
#define glVertexAttribI4usv opengl_core_VertexAttribI4usv
#define glGetVertexAttribIiv opengl_core_GetVertexAttribIiv
#define glGetTexParameterIiv opengl_core_GetTexParameterIiv
#define glGetVertexAttribIuiv opengl_core_GetVertexAttribIuiv
#define glGetFragDataLocation opengl_core_GetFragDataLocation
#define glGetTexParameterIuiv opengl_core_GetTexParameterIuiv
#define glEndTransformFeedback opengl_core_EndTransformFeedback
#define glEndConditionalRender opengl_core_EndConditionalRender
#define glVertexAttribIPointer opengl_core_VertexAttribIPointer
#define glBindFragDataLocation opengl_core_BindFragDataLocation
#define glBeginTransformFeedback opengl_core_BeginTransformFeedback
#define glBeginConditionalRender opengl_core_BeginConditionalRender
#define glTransformFeedbackVaryings opengl_core_TransformFeedbackVaryings
#define glGetTransformFeedbackVarying opengl_core_GetTransformFeedbackVarying

#include <GL/gl.h>
#include <GL/glext.h>

// Bootstrap function for OpenGL 3.0 and greater
extern OPENGL_CORE_API PFNGLGETSTRINGIPROC opengl_core_GetStringi;

// OpenGL 1.2
extern OPENGL_CORE_API PFNGLMINMAXPROC opengl_core_Minmax;
extern OPENGL_CORE_API PFNGLGETMINMAXPROC opengl_core_GetMinmax;
extern OPENGL_CORE_API PFNGLHISTOGRAMPROC opengl_core_Histogram;
extern OPENGL_CORE_API PFNGLBLENDCOLORPROC opengl_core_BlendColor;
extern OPENGL_CORE_API PFNGLCOLORTABLEPROC opengl_core_ColorTable;
extern OPENGL_CORE_API PFNGLTEXIMAGE3DPROC opengl_core_TexImage3D;
extern OPENGL_CORE_API PFNGLRESETMINMAXPROC opengl_core_ResetMinmax;
extern OPENGL_CORE_API PFNGLGETHISTOGRAMPROC opengl_core_GetHistogram;
extern OPENGL_CORE_API PFNGLBLENDEQUATIONPROC opengl_core_BlendEquation;
extern OPENGL_CORE_API PFNGLGETCOLORTABLEPROC opengl_core_GetColorTable;
extern OPENGL_CORE_API PFNGLCOLORSUBTABLEPROC opengl_core_ColorSubTable;
extern OPENGL_CORE_API PFNGLTEXSUBIMAGE3DPROC opengl_core_TexSubImage3D;
extern OPENGL_CORE_API PFNGLCOPYCOLORTABLEPROC opengl_core_CopyColorTable;
extern OPENGL_CORE_API PFNGLRESETHISTOGRAMPROC opengl_core_ResetHistogram;
extern OPENGL_CORE_API PFNGLDRAWRANGEELEMENTSPROC opengl_core_DrawRangeElements;
extern OPENGL_CORE_API PFNGLCOPYCOLORSUBTABLEPROC opengl_core_CopyColorSubTable;
extern OPENGL_CORE_API PFNGLSEPARABLEFILTER2DPROC opengl_core_SeparableFilter2D;
extern OPENGL_CORE_API PFNGLCOPYTEXSUBIMAGE3DPROC opengl_core_CopyTexSubImage3D;
extern OPENGL_CORE_API PFNGLGETSEPARABLEFILTERPROC opengl_core_GetSeparableFilter;
extern OPENGL_CORE_API PFNGLCONVOLUTIONFILTER1DPROC opengl_core_ConvolutionFilter1D;
extern OPENGL_CORE_API PFNGLCONVOLUTIONFILTER2DPROC opengl_core_ConvolutionFilter2D;
extern OPENGL_CORE_API PFNGLGETCONVOLUTIONFILTERPROC opengl_core_GetConvolutionFilter;
extern OPENGL_CORE_API PFNGLGETMINMAXPARAMETERFVPROC opengl_core_GetMinmaxParameterfv;
extern OPENGL_CORE_API PFNGLGETMINMAXPARAMETERIVPROC opengl_core_GetMinmaxParameteriv;
extern OPENGL_CORE_API PFNGLCOLORTABLEPARAMETERFVPROC opengl_core_ColorTableParameterfv;
extern OPENGL_CORE_API PFNGLCOLORTABLEPARAMETERIVPROC opengl_core_ColorTableParameteriv;
extern OPENGL_CORE_API PFNGLCONVOLUTIONPARAMETERFPROC opengl_core_ConvolutionParameterf;
extern OPENGL_CORE_API PFNGLCONVOLUTIONPARAMETERIPROC opengl_core_ConvolutionParameteri;
extern OPENGL_CORE_API PFNGLCONVOLUTIONPARAMETERFVPROC opengl_core_ConvolutionParameterfv;
extern OPENGL_CORE_API PFNGLCONVOLUTIONPARAMETERIVPROC opengl_core_ConvolutionParameteriv;
extern OPENGL_CORE_API PFNGLCOPYCONVOLUTIONFILTER1DPROC opengl_core_CopyConvolutionFilter1D;
extern OPENGL_CORE_API PFNGLCOPYCONVOLUTIONFILTER2DPROC opengl_core_CopyConvolutionFilter2D;
extern OPENGL_CORE_API PFNGLGETHISTOGRAMPARAMETERFVPROC opengl_core_GetHistogramParameterfv;
extern OPENGL_CORE_API PFNGLGETHISTOGRAMPARAMETERIVPROC opengl_core_GetHistogramParameteriv;
extern OPENGL_CORE_API PFNGLGETCOLORTABLEPARAMETERFVPROC opengl_core_GetColorTableParameterfv;
extern OPENGL_CORE_API PFNGLGETCOLORTABLEPARAMETERIVPROC opengl_core_GetColorTableParameteriv;
extern OPENGL_CORE_API PFNGLGETCONVOLUTIONPARAMETERFVPROC opengl_core_GetConvolutionParameterfv;
extern OPENGL_CORE_API PFNGLGETCONVOLUTIONPARAMETERIVPROC opengl_core_GetConvolutionParameteriv;

// OpenGL 1.3
extern OPENGL_CORE_API PFNGLACTIVETEXTUREPROC opengl_core_ActiveTexture;
extern OPENGL_CORE_API PFNGLSAMPLECOVERAGEPROC opengl_core_SampleCoverage;
extern OPENGL_CORE_API PFNGLMULTITEXCOORD1DPROC opengl_core_MultiTexCoord1d;
extern OPENGL_CORE_API PFNGLMULTITEXCOORD1FPROC opengl_core_MultiTexCoord1f;
extern OPENGL_CORE_API PFNGLMULTITEXCOORD1IPROC opengl_core_MultiTexCoord1i;
extern OPENGL_CORE_API PFNGLMULTITEXCOORD1SPROC opengl_core_MultiTexCoord1s;
extern OPENGL_CORE_API PFNGLMULTITEXCOORD2DPROC opengl_core_MultiTexCoord2d;
extern OPENGL_CORE_API PFNGLMULTITEXCOORD2FPROC opengl_core_MultiTexCoord2f;
extern OPENGL_CORE_API PFNGLMULTITEXCOORD2IPROC opengl_core_MultiTexCoord2i;
extern OPENGL_CORE_API PFNGLMULTITEXCOORD2SPROC opengl_core_MultiTexCoord2s;
extern OPENGL_CORE_API PFNGLMULTITEXCOORD3DPROC opengl_core_MultiTexCoord3d;
extern OPENGL_CORE_API PFNGLMULTITEXCOORD3FPROC opengl_core_MultiTexCoord3f;
extern OPENGL_CORE_API PFNGLMULTITEXCOORD3IPROC opengl_core_MultiTexCoord3i;
extern OPENGL_CORE_API PFNGLMULTITEXCOORD3SPROC opengl_core_MultiTexCoord3s;
extern OPENGL_CORE_API PFNGLMULTITEXCOORD4DPROC opengl_core_MultiTexCoord4d;
extern OPENGL_CORE_API PFNGLMULTITEXCOORD4FPROC opengl_core_MultiTexCoord4f;
extern OPENGL_CORE_API PFNGLMULTITEXCOORD4IPROC opengl_core_MultiTexCoord4i;
extern OPENGL_CORE_API PFNGLMULTITEXCOORD4SPROC opengl_core_MultiTexCoord4s;
extern OPENGL_CORE_API PFNGLMULTITEXCOORD1DVPROC opengl_core_MultiTexCoord1dv;
extern OPENGL_CORE_API PFNGLMULTITEXCOORD1FVPROC opengl_core_MultiTexCoord1fv;
extern OPENGL_CORE_API PFNGLMULTITEXCOORD1IVPROC opengl_core_MultiTexCoord1iv;
extern OPENGL_CORE_API PFNGLMULTITEXCOORD1SVPROC opengl_core_MultiTexCoord1sv;
extern OPENGL_CORE_API PFNGLMULTITEXCOORD2DVPROC opengl_core_MultiTexCoord2dv;
extern OPENGL_CORE_API PFNGLMULTITEXCOORD2FVPROC opengl_core_MultiTexCoord2fv;
extern OPENGL_CORE_API PFNGLMULTITEXCOORD2IVPROC opengl_core_MultiTexCoord2iv;
extern OPENGL_CORE_API PFNGLMULTITEXCOORD2SVPROC opengl_core_MultiTexCoord2sv;
extern OPENGL_CORE_API PFNGLMULTITEXCOORD3DVPROC opengl_core_MultiTexCoord3dv;
extern OPENGL_CORE_API PFNGLMULTITEXCOORD3FVPROC opengl_core_MultiTexCoord3fv;
extern OPENGL_CORE_API PFNGLMULTITEXCOORD3IVPROC opengl_core_MultiTexCoord3iv;
extern OPENGL_CORE_API PFNGLMULTITEXCOORD3SVPROC opengl_core_MultiTexCoord3sv;
extern OPENGL_CORE_API PFNGLMULTITEXCOORD4DVPROC opengl_core_MultiTexCoord4dv;
extern OPENGL_CORE_API PFNGLMULTITEXCOORD4FVPROC opengl_core_MultiTexCoord4fv;
extern OPENGL_CORE_API PFNGLMULTITEXCOORD4IVPROC opengl_core_MultiTexCoord4iv;
extern OPENGL_CORE_API PFNGLMULTITEXCOORD4SVPROC opengl_core_MultiTexCoord4sv;
extern OPENGL_CORE_API PFNGLCLIENTACTIVETEXTUREPROC opengl_core_ClientActiveTexture;
extern OPENGL_CORE_API PFNGLLOADTRANSPOSEMATRIXFPROC opengl_core_LoadTransposeMatrixf;
extern OPENGL_CORE_API PFNGLLOADTRANSPOSEMATRIXDPROC opengl_core_LoadTransposeMatrixd;
extern OPENGL_CORE_API PFNGLMULTTRANSPOSEMATRIXFPROC opengl_core_MultTransposeMatrixf;
extern OPENGL_CORE_API PFNGLMULTTRANSPOSEMATRIXDPROC opengl_core_MultTransposeMatrixd;
extern OPENGL_CORE_API PFNGLCOMPRESSEDTEXIMAGE3DPROC opengl_core_CompressedTexImage3D;
extern OPENGL_CORE_API PFNGLCOMPRESSEDTEXIMAGE2DPROC opengl_core_CompressedTexImage2D;
extern OPENGL_CORE_API PFNGLCOMPRESSEDTEXIMAGE1DPROC opengl_core_CompressedTexImage1D;
extern OPENGL_CORE_API PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC opengl_core_CompressedTexSubImage3D;
extern OPENGL_CORE_API PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC opengl_core_CompressedTexSubImage2D;
extern OPENGL_CORE_API PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC opengl_core_CompressedTexSubImage1D;

// OpenGL 1.4
extern OPENGL_CORE_API PFNGLFOGCOORDFPROC opengl_core_FogCoordf;
extern OPENGL_CORE_API PFNGLFOGCOORDDPROC opengl_core_FogCoordd;
extern OPENGL_CORE_API PFNGLFOGCOORDFVPROC opengl_core_FogCoordfv;
extern OPENGL_CORE_API PFNGLFOGCOORDDVPROC opengl_core_FogCoorddv;
extern OPENGL_CORE_API PFNGLWINDOWPOS2DPROC opengl_core_WindowPos2d;
extern OPENGL_CORE_API PFNGLWINDOWPOS2FPROC opengl_core_WindowPos2f;
extern OPENGL_CORE_API PFNGLWINDOWPOS2IPROC opengl_core_WindowPos2i;
extern OPENGL_CORE_API PFNGLWINDOWPOS2SPROC opengl_core_WindowPos2s;
extern OPENGL_CORE_API PFNGLWINDOWPOS3DPROC opengl_core_WindowPos3d;
extern OPENGL_CORE_API PFNGLWINDOWPOS3FPROC opengl_core_WindowPos3f;
extern OPENGL_CORE_API PFNGLWINDOWPOS3IPROC opengl_core_WindowPos3i;
extern OPENGL_CORE_API PFNGLWINDOWPOS3SPROC opengl_core_WindowPos3s;
extern OPENGL_CORE_API PFNGLWINDOWPOS2DVPROC opengl_core_WindowPos2dv;
extern OPENGL_CORE_API PFNGLWINDOWPOS2FVPROC opengl_core_WindowPos2fv;
extern OPENGL_CORE_API PFNGLWINDOWPOS2IVPROC opengl_core_WindowPos2iv;
extern OPENGL_CORE_API PFNGLWINDOWPOS2SVPROC opengl_core_WindowPos2sv;
extern OPENGL_CORE_API PFNGLWINDOWPOS3DVPROC opengl_core_WindowPos3dv;
extern OPENGL_CORE_API PFNGLWINDOWPOS3FVPROC opengl_core_WindowPos3fv;
extern OPENGL_CORE_API PFNGLWINDOWPOS3IVPROC opengl_core_WindowPos3iv;
extern OPENGL_CORE_API PFNGLWINDOWPOS3SVPROC opengl_core_WindowPos3sv;
extern OPENGL_CORE_API PFNGLFOGCOORDPOINTERPROC opengl_core_FogCoordPointer;
extern OPENGL_CORE_API PFNGLMULTIDRAWARRAYSPROC opengl_core_MultiDrawArrays;
extern OPENGL_CORE_API PFNGLPOINTPARAMETERFPROC opengl_core_PointParameterf;
extern OPENGL_CORE_API PFNGLPOINTPARAMETERIPROC opengl_core_PointParameteri;
extern OPENGL_CORE_API PFNGLPOINTPARAMETERFVPROC opengl_core_PointParameterfv;
extern OPENGL_CORE_API PFNGLPOINTPARAMETERIVPROC opengl_core_PointParameteriv;
extern OPENGL_CORE_API PFNGLSECONDARYCOLOR3BPROC opengl_core_SecondaryColor3b;
extern OPENGL_CORE_API PFNGLSECONDARYCOLOR3DPROC opengl_core_SecondaryColor3d;
extern OPENGL_CORE_API PFNGLSECONDARYCOLOR3FPROC opengl_core_SecondaryColor3f;
extern OPENGL_CORE_API PFNGLSECONDARYCOLOR3IPROC opengl_core_SecondaryColor3i;
extern OPENGL_CORE_API PFNGLSECONDARYCOLOR3SPROC opengl_core_SecondaryColor3s;
extern OPENGL_CORE_API PFNGLBLENDFUNCSEPARATEPROC opengl_core_BlendFuncSeparate;
extern OPENGL_CORE_API PFNGLMULTIDRAWELEMENTSPROC opengl_core_MultiDrawElements;
extern OPENGL_CORE_API PFNGLSECONDARYCOLOR3BVPROC opengl_core_SecondaryColor3bv;
extern OPENGL_CORE_API PFNGLSECONDARYCOLOR3DVPROC opengl_core_SecondaryColor3dv;
extern OPENGL_CORE_API PFNGLSECONDARYCOLOR3FVPROC opengl_core_SecondaryColor3fv;
extern OPENGL_CORE_API PFNGLSECONDARYCOLOR3IVPROC opengl_core_SecondaryColor3iv;
extern OPENGL_CORE_API PFNGLSECONDARYCOLOR3SVPROC opengl_core_SecondaryColor3sv;
extern OPENGL_CORE_API PFNGLSECONDARYCOLOR3UBPROC opengl_core_SecondaryColor3ub;
extern OPENGL_CORE_API PFNGLSECONDARYCOLOR3UIPROC opengl_core_SecondaryColor3ui;
extern OPENGL_CORE_API PFNGLSECONDARYCOLOR3USPROC opengl_core_SecondaryColor3us;
extern OPENGL_CORE_API PFNGLSECONDARYCOLOR3UBVPROC opengl_core_SecondaryColor3ubv;
extern OPENGL_CORE_API PFNGLSECONDARYCOLOR3UIVPROC opengl_core_SecondaryColor3uiv;
extern OPENGL_CORE_API PFNGLSECONDARYCOLOR3USVPROC opengl_core_SecondaryColor3usv;
extern OPENGL_CORE_API PFNGLSECONDARYCOLORPOINTERPROC opengl_core_SecondaryColorPointer;

// OpenGL 1.5
extern OPENGL_CORE_API PFNGLISQUERYPROC opengl_core_IsQuery;
extern OPENGL_CORE_API PFNGLENDQUERYPROC opengl_core_EndQuery;
extern OPENGL_CORE_API PFNGLISBUFFERPROC opengl_core_IsBuffer;
extern OPENGL_CORE_API PFNGLMAPBUFFERPROC opengl_core_MapBuffer;
extern OPENGL_CORE_API PFNGLGENQUERIESPROC opengl_core_GenQueries;
extern OPENGL_CORE_API PFNGLBEGINQUERYPROC opengl_core_BeginQuery;
extern OPENGL_CORE_API PFNGLGETQUERYIVPROC opengl_core_GetQueryiv;
extern OPENGL_CORE_API PFNGLBINDBUFFERPROC opengl_core_BindBuffer;
extern OPENGL_CORE_API PFNGLGENBUFFERSPROC opengl_core_GenBuffers;
extern OPENGL_CORE_API PFNGLBUFFERDATAPROC opengl_core_BufferData;
extern OPENGL_CORE_API PFNGLUNMAPBUFFERPROC opengl_core_UnmapBuffer;
extern OPENGL_CORE_API PFNGLDELETEQUERIESPROC opengl_core_DeleteQueries;
extern OPENGL_CORE_API PFNGLDELETEBUFFERSPROC opengl_core_DeleteBuffers;
extern OPENGL_CORE_API PFNGLBUFFERSUBDATAPROC opengl_core_BufferSubData;
extern OPENGL_CORE_API PFNGLGETQUERYOBJECTIVPROC opengl_core_GetQueryObjectiv;
extern OPENGL_CORE_API PFNGLGETBUFFERSUBDATAPROC opengl_core_GetBufferSubData;
extern OPENGL_CORE_API PFNGLGETQUERYOBJECTUIVPROC opengl_core_GetQueryObjectuiv;
extern OPENGL_CORE_API PFNGLGETBUFFERPOINTERVPROC opengl_core_GetBufferPointerv;
extern OPENGL_CORE_API PFNGLGETBUFFERPARAMETERIVPROC opengl_core_GetBufferParameteriv;

// OpenGL 2.0
extern OPENGL_CORE_API PFNGLISSHADERPROC opengl_core_IsShader;
extern OPENGL_CORE_API PFNGLISPROGRAMPROC opengl_core_IsProgram;
extern OPENGL_CORE_API PFNGLUNIFORM1FPROC opengl_core_Uniform1f;
extern OPENGL_CORE_API PFNGLUNIFORM2FPROC opengl_core_Uniform2f;
extern OPENGL_CORE_API PFNGLUNIFORM3FPROC opengl_core_Uniform3f;
extern OPENGL_CORE_API PFNGLUNIFORM4FPROC opengl_core_Uniform4f;
extern OPENGL_CORE_API PFNGLUNIFORM1IPROC opengl_core_Uniform1i;
extern OPENGL_CORE_API PFNGLUNIFORM2IPROC opengl_core_Uniform2i;
extern OPENGL_CORE_API PFNGLUNIFORM3IPROC opengl_core_Uniform3i;
extern OPENGL_CORE_API PFNGLUNIFORM4IPROC opengl_core_Uniform4i;
extern OPENGL_CORE_API PFNGLUSEPROGRAMPROC opengl_core_UseProgram;
extern OPENGL_CORE_API PFNGLUNIFORM1FVPROC opengl_core_Uniform1fv;
extern OPENGL_CORE_API PFNGLUNIFORM2FVPROC opengl_core_Uniform2fv;
extern OPENGL_CORE_API PFNGLUNIFORM3FVPROC opengl_core_Uniform3fv;
extern OPENGL_CORE_API PFNGLUNIFORM4FVPROC opengl_core_Uniform4fv;
extern OPENGL_CORE_API PFNGLUNIFORM1IVPROC opengl_core_Uniform1iv;
extern OPENGL_CORE_API PFNGLUNIFORM2IVPROC opengl_core_Uniform2iv;
extern OPENGL_CORE_API PFNGLUNIFORM3IVPROC opengl_core_Uniform3iv;
extern OPENGL_CORE_API PFNGLUNIFORM4IVPROC opengl_core_Uniform4iv;
extern OPENGL_CORE_API PFNGLDRAWBUFFERSPROC opengl_core_DrawBuffers;
extern OPENGL_CORE_API PFNGLGETSHADERIVPROC opengl_core_GetShaderiv;
extern OPENGL_CORE_API PFNGLLINKPROGRAMPROC opengl_core_LinkProgram;
extern OPENGL_CORE_API PFNGLATTACHSHADERPROC opengl_core_AttachShader;
extern OPENGL_CORE_API PFNGLCREATESHADERPROC opengl_core_CreateShader;
extern OPENGL_CORE_API PFNGLDELETESHADERPROC opengl_core_DeleteShader;
extern OPENGL_CORE_API PFNGLDETACHSHADERPROC opengl_core_DetachShader;
extern OPENGL_CORE_API PFNGLGETPROGRAMIVPROC opengl_core_GetProgramiv;
extern OPENGL_CORE_API PFNGLGETUNIFORMFVPROC opengl_core_GetUniformfv;
extern OPENGL_CORE_API PFNGLGETUNIFORMIVPROC opengl_core_GetUniformiv;
extern OPENGL_CORE_API PFNGLSHADERSOURCEPROC opengl_core_ShaderSource;
extern OPENGL_CORE_API PFNGLCOMPILESHADERPROC opengl_core_CompileShader;
extern OPENGL_CORE_API PFNGLCREATEPROGRAMPROC opengl_core_CreateProgram;
extern OPENGL_CORE_API PFNGLDELETEPROGRAMPROC opengl_core_DeleteProgram;
extern OPENGL_CORE_API PFNGLVERTEXATTRIB1DPROC opengl_core_VertexAttrib1d;
extern OPENGL_CORE_API PFNGLVERTEXATTRIB1FPROC opengl_core_VertexAttrib1f;
extern OPENGL_CORE_API PFNGLVERTEXATTRIB1SPROC opengl_core_VertexAttrib1s;
extern OPENGL_CORE_API PFNGLVERTEXATTRIB2DPROC opengl_core_VertexAttrib2d;
extern OPENGL_CORE_API PFNGLVERTEXATTRIB2FPROC opengl_core_VertexAttrib2f;
extern OPENGL_CORE_API PFNGLVERTEXATTRIB2SPROC opengl_core_VertexAttrib2s;
extern OPENGL_CORE_API PFNGLVERTEXATTRIB3DPROC opengl_core_VertexAttrib3d;
extern OPENGL_CORE_API PFNGLVERTEXATTRIB3FPROC opengl_core_VertexAttrib3f;
extern OPENGL_CORE_API PFNGLVERTEXATTRIB3SPROC opengl_core_VertexAttrib3s;
extern OPENGL_CORE_API PFNGLVERTEXATTRIB4DPROC opengl_core_VertexAttrib4d;
extern OPENGL_CORE_API PFNGLVERTEXATTRIB4FPROC opengl_core_VertexAttrib4f;
extern OPENGL_CORE_API PFNGLVERTEXATTRIB4SPROC opengl_core_VertexAttrib4s;
extern OPENGL_CORE_API PFNGLGETACTIVEATTRIBPROC opengl_core_GetActiveAttrib;
extern OPENGL_CORE_API PFNGLGETSHADERSOURCEPROC opengl_core_GetShaderSource;
extern OPENGL_CORE_API PFNGLVALIDATEPROGRAMPROC opengl_core_ValidateProgram;
extern OPENGL_CORE_API PFNGLVERTEXATTRIB1DVPROC opengl_core_VertexAttrib1dv;
extern OPENGL_CORE_API PFNGLVERTEXATTRIB1FVPROC opengl_core_VertexAttrib1fv;
extern OPENGL_CORE_API PFNGLVERTEXATTRIB1SVPROC opengl_core_VertexAttrib1sv;
extern OPENGL_CORE_API PFNGLVERTEXATTRIB2DVPROC opengl_core_VertexAttrib2dv;
extern OPENGL_CORE_API PFNGLVERTEXATTRIB2FVPROC opengl_core_VertexAttrib2fv;
extern OPENGL_CORE_API PFNGLVERTEXATTRIB2SVPROC opengl_core_VertexAttrib2sv;
extern OPENGL_CORE_API PFNGLVERTEXATTRIB3DVPROC opengl_core_VertexAttrib3dv;
extern OPENGL_CORE_API PFNGLVERTEXATTRIB3FVPROC opengl_core_VertexAttrib3fv;
extern OPENGL_CORE_API PFNGLVERTEXATTRIB3SVPROC opengl_core_VertexAttrib3sv;
extern OPENGL_CORE_API PFNGLVERTEXATTRIB4BVPROC opengl_core_VertexAttrib4bv;
extern OPENGL_CORE_API PFNGLVERTEXATTRIB4DVPROC opengl_core_VertexAttrib4dv;
extern OPENGL_CORE_API PFNGLVERTEXATTRIB4FVPROC opengl_core_VertexAttrib4fv;
extern OPENGL_CORE_API PFNGLVERTEXATTRIB4IVPROC opengl_core_VertexAttrib4iv;
extern OPENGL_CORE_API PFNGLVERTEXATTRIB4SVPROC opengl_core_VertexAttrib4sv;
extern OPENGL_CORE_API PFNGLGETACTIVEUNIFORMPROC opengl_core_GetActiveUniform;
extern OPENGL_CORE_API PFNGLGETSHADERINFOLOGPROC opengl_core_GetShaderInfoLog;
extern OPENGL_CORE_API PFNGLUNIFORMMATRIX2FVPROC opengl_core_UniformMatrix2fv;
extern OPENGL_CORE_API PFNGLUNIFORMMATRIX3FVPROC opengl_core_UniformMatrix3fv;
extern OPENGL_CORE_API PFNGLUNIFORMMATRIX4FVPROC opengl_core_UniformMatrix4fv;
extern OPENGL_CORE_API PFNGLVERTEXATTRIB4NBVPROC opengl_core_VertexAttrib4Nbv;
extern OPENGL_CORE_API PFNGLVERTEXATTRIB4NIVPROC opengl_core_VertexAttrib4Niv;
extern OPENGL_CORE_API PFNGLVERTEXATTRIB4NSVPROC opengl_core_VertexAttrib4Nsv;
extern OPENGL_CORE_API PFNGLVERTEXATTRIB4NUBPROC opengl_core_VertexAttrib4Nub;
extern OPENGL_CORE_API PFNGLVERTEXATTRIB4UBVPROC opengl_core_VertexAttrib4ubv;
extern OPENGL_CORE_API PFNGLVERTEXATTRIB4UIVPROC opengl_core_VertexAttrib4uiv;
extern OPENGL_CORE_API PFNGLVERTEXATTRIB4USVPROC opengl_core_VertexAttrib4usv;
extern OPENGL_CORE_API PFNGLSTENCILOPSEPARATEPROC opengl_core_StencilOpSeparate;
extern OPENGL_CORE_API PFNGLGETATTRIBLOCATIONPROC opengl_core_GetAttribLocation;
extern OPENGL_CORE_API PFNGLGETPROGRAMINFOLOGPROC opengl_core_GetProgramInfoLog;
extern OPENGL_CORE_API PFNGLGETVERTEXATTRIBDVPROC opengl_core_GetVertexAttribdv;
extern OPENGL_CORE_API PFNGLGETVERTEXATTRIBFVPROC opengl_core_GetVertexAttribfv;
extern OPENGL_CORE_API PFNGLGETVERTEXATTRIBIVPROC opengl_core_GetVertexAttribiv;
extern OPENGL_CORE_API PFNGLVERTEXATTRIB4NUBVPROC opengl_core_VertexAttrib4Nubv;
extern OPENGL_CORE_API PFNGLVERTEXATTRIB4NUIVPROC opengl_core_VertexAttrib4Nuiv;
extern OPENGL_CORE_API PFNGLVERTEXATTRIB4NUSVPROC opengl_core_VertexAttrib4Nusv;
extern OPENGL_CORE_API PFNGLBINDATTRIBLOCATIONPROC opengl_core_BindAttribLocation;
extern OPENGL_CORE_API PFNGLGETATTACHEDSHADERSPROC opengl_core_GetAttachedShaders;
extern OPENGL_CORE_API PFNGLGETUNIFORMLOCATIONPROC opengl_core_GetUniformLocation;
extern OPENGL_CORE_API PFNGLSTENCILFUNCSEPARATEPROC opengl_core_StencilFuncSeparate;
extern OPENGL_CORE_API PFNGLSTENCILMASKSEPARATEPROC opengl_core_StencilMaskSeparate;
extern OPENGL_CORE_API PFNGLVERTEXATTRIBPOINTERPROC opengl_core_VertexAttribPointer;
extern OPENGL_CORE_API PFNGLBLENDEQUATIONSEPARATEPROC opengl_core_BlendEquationSeparate;
extern OPENGL_CORE_API PFNGLENABLEVERTEXATTRIBARRAYPROC opengl_core_EnableVertexAttribArray;
extern OPENGL_CORE_API PFNGLGETVERTEXATTRIBPOINTERVPROC opengl_core_GetVertexAttribPointerv;
extern OPENGL_CORE_API PFNGLDISABLEVERTEXATTRIBARRAYPROC opengl_core_DisableVertexAttribArray;

// OpenGL 2.1
extern OPENGL_CORE_API PFNGLUNIFORMMATRIX2X3FVPROC opengl_core_UniformMatrix2x3fv;
extern OPENGL_CORE_API PFNGLUNIFORMMATRIX3X2FVPROC opengl_core_UniformMatrix3x2fv;
extern OPENGL_CORE_API PFNGLUNIFORMMATRIX2X4FVPROC opengl_core_UniformMatrix2x4fv;
extern OPENGL_CORE_API PFNGLUNIFORMMATRIX4X2FVPROC opengl_core_UniformMatrix4x2fv;
extern OPENGL_CORE_API PFNGLUNIFORMMATRIX3X4FVPROC opengl_core_UniformMatrix3x4fv;
extern OPENGL_CORE_API PFNGLUNIFORMMATRIX4X3FVPROC opengl_core_UniformMatrix4x3fv;

// OpenGL 3.0
// OpenGL 3.0 also reuses entry points from these extensions:
//  ARB_framebuffer_object
//  ARB_map_buffer_range
//  ARB_vertex_array_object
extern OPENGL_CORE_API PFNGLENABLEIPROC opengl_core_Enablei;
extern OPENGL_CORE_API PFNGLDISABLEIPROC opengl_core_Disablei;
extern OPENGL_CORE_API PFNGLCOLORMASKIPROC opengl_core_ColorMaski;
extern OPENGL_CORE_API PFNGLISENABLEDIPROC opengl_core_IsEnabledi;
extern OPENGL_CORE_API PFNGLCLAMPCOLORPROC opengl_core_ClampColor;
extern OPENGL_CORE_API PFNGLUNIFORM1UIPROC opengl_core_Uniform1ui;
extern OPENGL_CORE_API PFNGLUNIFORM2UIPROC opengl_core_Uniform2ui;
extern OPENGL_CORE_API PFNGLUNIFORM3UIPROC opengl_core_Uniform3ui;
extern OPENGL_CORE_API PFNGLUNIFORM4UIPROC opengl_core_Uniform4ui;
extern OPENGL_CORE_API PFNGLUNIFORM1UIVPROC opengl_core_Uniform1uiv;
extern OPENGL_CORE_API PFNGLUNIFORM2UIVPROC opengl_core_Uniform2uiv;
extern OPENGL_CORE_API PFNGLUNIFORM3UIVPROC opengl_core_Uniform3uiv;
extern OPENGL_CORE_API PFNGLUNIFORM4UIVPROC opengl_core_Uniform4uiv;
extern OPENGL_CORE_API PFNGLGETBOOLEANI_VPROC opengl_core_GetBooleani_v;
extern OPENGL_CORE_API PFNGLGETINTEGERI_VPROC opengl_core_GetIntegeri_v;
extern OPENGL_CORE_API PFNGLGETUNIFORMUIVPROC opengl_core_GetUniformuiv;
extern OPENGL_CORE_API PFNGLCLEARBUFFERIVPROC opengl_core_ClearBufferiv;
extern OPENGL_CORE_API PFNGLCLEARBUFFERFVPROC opengl_core_ClearBufferfv;
extern OPENGL_CORE_API PFNGLCLEARBUFFERFIPROC opengl_core_ClearBufferfi;
extern OPENGL_CORE_API PFNGLBINDBUFFERBASEPROC opengl_core_BindBufferBase;
extern OPENGL_CORE_API PFNGLCLEARBUFFERUIVPROC opengl_core_ClearBufferuiv;
extern OPENGL_CORE_API PFNGLBINDBUFFERRANGEPROC opengl_core_BindBufferRange;
extern OPENGL_CORE_API PFNGLVERTEXATTRIBI1IPROC opengl_core_VertexAttribI1i;
extern OPENGL_CORE_API PFNGLVERTEXATTRIBI2IPROC opengl_core_VertexAttribI2i;
extern OPENGL_CORE_API PFNGLVERTEXATTRIBI3IPROC opengl_core_VertexAttribI3i;
extern OPENGL_CORE_API PFNGLVERTEXATTRIBI4IPROC opengl_core_VertexAttribI4i;
extern OPENGL_CORE_API PFNGLTEXPARAMETERIIVPROC opengl_core_TexParameterIiv;
extern OPENGL_CORE_API PFNGLVERTEXATTRIBI1UIPROC opengl_core_VertexAttribI1ui;
extern OPENGL_CORE_API PFNGLVERTEXATTRIBI2UIPROC opengl_core_VertexAttribI2ui;
extern OPENGL_CORE_API PFNGLVERTEXATTRIBI3UIPROC opengl_core_VertexAttribI3ui;
extern OPENGL_CORE_API PFNGLVERTEXATTRIBI4UIPROC opengl_core_VertexAttribI4ui;
extern OPENGL_CORE_API PFNGLVERTEXATTRIBI1IVPROC opengl_core_VertexAttribI1iv;
extern OPENGL_CORE_API PFNGLVERTEXATTRIBI2IVPROC opengl_core_VertexAttribI2iv;
extern OPENGL_CORE_API PFNGLVERTEXATTRIBI3IVPROC opengl_core_VertexAttribI3iv;
extern OPENGL_CORE_API PFNGLVERTEXATTRIBI4IVPROC opengl_core_VertexAttribI4iv;
extern OPENGL_CORE_API PFNGLVERTEXATTRIBI4BVPROC opengl_core_VertexAttribI4bv;
extern OPENGL_CORE_API PFNGLVERTEXATTRIBI4SVPROC opengl_core_VertexAttribI4sv;
extern OPENGL_CORE_API PFNGLTEXPARAMETERIUIVPROC opengl_core_TexParameterIuiv;
extern OPENGL_CORE_API PFNGLVERTEXATTRIBI1UIVPROC opengl_core_VertexAttribI1uiv;
extern OPENGL_CORE_API PFNGLVERTEXATTRIBI2UIVPROC opengl_core_VertexAttribI2uiv;
extern OPENGL_CORE_API PFNGLVERTEXATTRIBI3UIVPROC opengl_core_VertexAttribI3uiv;
extern OPENGL_CORE_API PFNGLVERTEXATTRIBI4UIVPROC opengl_core_VertexAttribI4uiv;
extern OPENGL_CORE_API PFNGLVERTEXATTRIBI4UBVPROC opengl_core_VertexAttribI4ubv;
extern OPENGL_CORE_API PFNGLVERTEXATTRIBI4USVPROC opengl_core_VertexAttribI4usv;
extern OPENGL_CORE_API PFNGLGETVERTEXATTRIBIIVPROC opengl_core_GetVertexAttribIiv;
extern OPENGL_CORE_API PFNGLGETTEXPARAMETERIIVPROC opengl_core_GetTexParameterIiv;
extern OPENGL_CORE_API PFNGLGETVERTEXATTRIBIUIVPROC opengl_core_GetVertexAttribIuiv;
extern OPENGL_CORE_API PFNGLGETFRAGDATALOCATIONPROC opengl_core_GetFragDataLocation;
extern OPENGL_CORE_API PFNGLGETTEXPARAMETERIUIVPROC opengl_core_GetTexParameterIuiv;
extern OPENGL_CORE_API PFNGLENDTRANSFORMFEEDBACKPROC opengl_core_EndTransformFeedback;
extern OPENGL_CORE_API PFNGLENDCONDITIONALRENDERPROC opengl_core_EndConditionalRender;
extern OPENGL_CORE_API PFNGLVERTEXATTRIBIPOINTERPROC opengl_core_VertexAttribIPointer;
extern OPENGL_CORE_API PFNGLBINDFRAGDATALOCATIONPROC opengl_core_BindFragDataLocation;
extern OPENGL_CORE_API PFNGLBEGINTRANSFORMFEEDBACKPROC opengl_core_BeginTransformFeedback;
extern OPENGL_CORE_API PFNGLBEGINCONDITIONALRENDERPROC opengl_core_BeginConditionalRender;
extern OPENGL_CORE_API PFNGLTRANSFORMFEEDBACKVARYINGSPROC opengl_core_TransformFeedbackVaryings;
extern OPENGL_CORE_API PFNGLGETTRANSFORMFEEDBACKVARYINGPROC opengl_core_GetTransformFeedbackVarying;
*/
#endif
